### ISSUE TITLE
How to use the JS lib in the frontend?

### ISSUE THREAD

**Issue by mestaritonttu** [eno-lang/enolib#15]
How can I produce a version of the JS lib that can be used client side? I tried Browserify and Rollup, but the outputted file still contains instances of require().

**Comment by simonrepp** [comment]
I'm so far using https://parceljs.org/ (v1 for now as I didn't migrate to v2 yet) to produce the two isolated javascript application bundles on eno-lang.org that use enolib client-side in the browser (the [eno playground](https://eno-lang.org/playground/) and [enolib playground](https://eno-lang.org/enolib-playground/)).

Both bundler invocations can be found in the package scripts for eno-lang.org:
https://github.com/eno-lang/eno-lang.org/blob/a93c4f1ee461668535ae2f9960619bbaa2eb95d7/package.json#L32-L33

The respective files being built (which both import enolib) are [playground.js](https://github.com/eno-lang/eno-lang.org/blob/main/src/playground.js) and [enolib_playground.js](https://github.com/eno-lang/eno-lang.org/blob/main/src/enolib_playground.js).

I believe in the past I have also used webpack for this, but I'd need to dig around a bit to find that again.

Let me know if these examples/links help you out, fingers crossed! If you want to share your results afterwards (given it's a public thing anyway) I'd be curious to have a look too ;) feel free to post a link if that's the case!

**Comment by mestaritonttu** [comment]
Thanks a lot, it is working! Instead of just glancing at the code, I should have tested the Browserify and Rollup outputs as well - looks like they define a require() function like Parcel. But I will stick with Parcel (used 1.12.5).

I used a file like this:
```
import enolib, { parse, HtmlReporter, ParseError } from 'enolib';
const test = `name: test`; // imagine multi-line eno data here
const doc = enolib.parse(test); 
console.log(doc.field('name').requiredStringValue());
```
and built with
`parcel build enorequire.js --no-source-maps --out-dir ./ --out-file enolib.js`

**Comment by simonrepp** [comment]
Fantastic, great to hear it's working! :)
